name: Publish Packages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish Telegram.Bot.CommandHandler
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: TelegramCommandHandler/CommandHandler.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish Telegram.Bot.InteractivityHelper
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: TelegramInteractivityHelper/Interactivity.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    
